### ISSUE TITLE
Update WHOIS info with title

### ISSUE THREAD

**Issue by gabek** [jwise/dnairc-bridge#1]
The title of the current video/event now comes through the websocket.  I was thinking about maybe the bot sending a `NOTICE` when it changes, but that would get annoying.  So I thought maybe changing the `WHOIS` info might be a way to make that available without being annoying.

The message on the socket looks like this:
```
title	DNA Pizza Music Videos: Kittie -- What I Always Wanted (2001)
```

**Comment by jwise** [comment]
I think you can't update WHOIS while you're connected (that's the `USER` command that you send at the beginning of the connection).  One option is to make it change the `TOPIC`?

**Comment by gabek** [comment]
Oh right!  Forgot about that.  I was thinking of something that wouldn't flood the channel (since the channel is quite often idle, and you'd hate to see hundreds of bot topic changes, notices or messages of stuff that happened that you don't care about).  Probably not worth investigating, but if I come up with another idea I'll throw it out there!
